const params = new URLSearchParams(window.location.search);
const projectKey = params.get('project');
const project = window.portfolioData.projects.find(({ slug }) => slug === projectKey) || window.portfolioData.projects[0];

document.title = `${project.title} | Amanuel Feyissa`;
document.querySelector('meta[name="description"]').setAttribute('content', `${project.description} — a case study by Amanuel Feyissa Kussa.`);
document.querySelector('#project-canonical').href = `https://amanuelfeyissa.kussa.workers.dev/project.html?project=${project.slug}`;
document.querySelector('#project-category').textContent = project.category;
document.querySelector('#project-number').textContent = `PROJECT // ${project.id}`;
document.querySelector('#project-title').textContent = project.title;
document.querySelector('#project-status').textContent = project.status;
document.querySelector('#project-intro').textContent = project.detailIntro;
document.querySelector('#project-tags').innerHTML = project.tags.map((tag) => `<span>${tag}</span>`).join('');
document.querySelector('#project-brief').textContent = project.brief;
const approachHeading = document.querySelector('#project-approach-heading');
const approachList = document.querySelector('#project-approach');
approachHeading.textContent = project.approachType === 'capabilities' ? 'Capabilities' : 'Approach';
approachList.className = `approach-list ${project.approachType === 'capabilities' ? 'capabilities' : 'steps'}`;
approachList.innerHTML = project.approach.map((item) => `<li>${item}</li>`).join('');
document.querySelector('#project-stats').innerHTML = project.outcomeStats.map(({ value, label }) => `<div><strong>${value}</strong><span>${label}</span></div>`).join('');
document.querySelector('#project-outcome').textContent = project.outcome;
document.querySelector('[data-short-name]').textContent = window.portfolioData.person.shortName;
document.querySelector('#year').textContent = new Date().getFullYear();
